services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localstack
    environment:
      - NODE_ENV=test
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_ENDPOINT=http://localstack:4566 # LocalStack endpoint
    ports:
      - "3000:3000" # Assuming app runs on port 3000

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: "" # Override entrypoint to run shell
    volumes:
      - ./setup-dynamodb.sh:/setup-dynamodb.sh
    command: "/setup-dynamodb.sh"

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack main endpoint
      - "4571:4571" # Lambda service endpoint (optional)
    environment:
      - SERVICES=apigateway,lambda,dynamodb # Enable required services
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack-data:/var/lib/localstack" # Persist LocalStack data
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for Lambda