name: domain1

on:
  push:
    branches:
      - main
      - develop
    paths:
      - domain1/**
  pull_request:
  workflow_dispatch: {}

jobs:
  run-test:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/shared-test-file.yml
    with:
      generate-report: yes
      coverage-path: coverage
