name: domain1

on:
  push:
    branches:
      - main
      - develop
    paths:
      - domain1/**
  pull_request:
  workflow_dispatch: {}

jobs:
  run-test:
    uses: ./.github/workflows/shared-test-file.yml
    with:
      service: domain1
      generate-report: yes
      actions: test
