name: Build and Test

on:
    workflow_call:
        inputs:
            generate-report:
                description: 'Generate coverage report'
                required: false
                type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version your project requires
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Unit Tests
      - name: Run Vitest
        run: npx vitest test/unit --coverage

      # Step 6: Check Coverage Changes      
      - name: Track coverage changes (no enforcement)
        run: npm run test:coverage-check

        # Step 7: Upload Coverage Artifact
      - name: Upload Coverage Report
        if: ${{ inputs.generate-report }}
        uses: actions/upload-artifact@v4
        with:
          name: vitest-coverage
          path: coverage/  